# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rm_pb2 as rm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08nm.proto\x1a\x08rm.proto2\xab\x02\n\x08NMServer\x12.\n\tLaunchJob\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12\x31\n\x0cTerminateJob\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12,\n\nGetMetrics\x12\r.JsonResponse\x1a\r.JsonResponse\"\x00\x12/\n\nSetMetrics\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12-\n\x08GetLease\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12.\n\x0fNotifyTerminate\x12\x07.IntVal\x1a\x10.BooleanResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NMSERVER']._serialized_start=23
  _globals['_NMSERVER']._serialized_end=322
# @@protoc_insertion_point(module_scope)
