# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08rm.proto\" \n\x0cJsonResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\xdc\x01\n\x0fRegisterRequest\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x0f\n\x07numGPUs\x18\x02 \x01(\x05\x12\x13\n\x0bnumCPUcores\x18\x03 \x01(\x05\x12\x16\n\x0ememoryCapacity\x18\x04 \x01(\x05\x12\x15\n\rnumaAvailable\x18\x05 \x01(\x08\x12\x32\n\tcpuMaping\x18\x06 \x03(\x0b\x32\x1f.RegisterRequest.CpuMapingEntry\x1a\x30\n\x0e\x43puMapingEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\" \n\x0f\x42ooleanResponse\x12\r\n\x05value\x18\x01 \x01(\x08\"\x17\n\x06IntVal\x12\r\n\x05value\x18\x01 \x01(\x05\"\n\n\x08\x45mptyMsg2\x96\x01\n\x08RMServer\x12\x36\n\x0eRegisterWorker\x12\x10.RegisterRequest\x1a\x10.BooleanResponse\"\x00\x12.\n\tAcceptJob\x12\r.JsonResponse\x1a\x10.BooleanResponse\"\x00\x12\"\n\nReturnTime\x12\t.EmptyMsg\x1a\x07.IntVal\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST_CPUMAPINGENTRY']._options = None
  _globals['_REGISTERREQUEST_CPUMAPINGENTRY']._serialized_options = b'8\001'
  _globals['_JSONRESPONSE']._serialized_start=12
  _globals['_JSONRESPONSE']._serialized_end=44
  _globals['_REGISTERREQUEST']._serialized_start=47
  _globals['_REGISTERREQUEST']._serialized_end=267
  _globals['_REGISTERREQUEST_CPUMAPINGENTRY']._serialized_start=219
  _globals['_REGISTERREQUEST_CPUMAPINGENTRY']._serialized_end=267
  _globals['_BOOLEANRESPONSE']._serialized_start=269
  _globals['_BOOLEANRESPONSE']._serialized_end=301
  _globals['_INTVAL']._serialized_start=303
  _globals['_INTVAL']._serialized_end=326
  _globals['_EMPTYMSG']._serialized_start=328
  _globals['_EMPTYMSG']._serialized_end=338
  _globals['_RMSERVER']._serialized_start=341
  _globals['_RMSERVER']._serialized_end=491
# @@protoc_insertion_point(module_scope)
